services:
  api:
    image: ghcr.io/xiaoyuanzhu-com/homelab-ai-in-docker:latest
    restart: unless-stopped
    container_name: homelab-ai-in-docker
    ports:
      - "8000:8000"
    volumes:
      - ./data:/haid/data
    environment:
      - PYTHONUNBUFFERED=1
      - PADDLE_PDX_CACHE_HOME=/haid/data/paddlex
      # Optional: Set default remote Chrome URL (e.g., http://172.16.2.2:9223)
      # - CHROME_CDP_URL=http://172.16.2.2:9223
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
