services:
  api:
    image: ghcr.io/xiaoyuanzhu-com/homelab-ai-in-docker:latest
    restart: unless-stopped
    container_name: homelab-ai-in-docker
    ports:
      - "8000:8000"
    volumes:
      - ./data:/haid/data
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
